name: DEPLOY_TO_DEV-1

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'image tag'
        required: true
        default: latest

jobs:
  deploy:
    runs-on: [self-hosted, build]
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-helm@v1
        with:
          version: 'v3.2.2'
      - name: Setup helm repo
        run: |
          helm repo add 0chain-helm http://0chain-helm-chart.s3-website.us-east-2.amazonaws.com/helmCharts/
          helm repo update
      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.DEV1KC }}" | base64 -d > ~/.kube/config
      - name: Setup chain
        run: |
          helm upgrade --install 0search -n dev-1 --set blockRecorder.blockRecorderImage.tag=${{ github.event.inputs.image }} --set blockRecorder.host=devnet-0chain.net 0chain-helm/zsearch
          rm -rf ~/.kube